### ISSUE TITLE
Timeout when trying to getLists in Office 365 in CakePHP 2.x

### ISSUE THREAD

**Issue by densonclan** [thybag/PHP-SharePoint-Lists-API#124]
Getting the following errors:

```
Error (Sender) Curl error: Connection timed out after 10000 milliseconds,more=
Error: An Internal Error Has Occurred.
Stack Trace
APP/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php line 280 → Thybag\SharePointAPI->onError(SoapFault)
object(SoapFault) {
	faultstring => 'Curl error: Connection timed out after 10000 milliseconds'
	faultcode => 'Sender'
	xdebug_message => '<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SoapFault: Curl error: Connection timed out after 10000 milliseconds in /www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/Auth/SharePointOnlineAuth.php on line <i>192</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>359120</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/www/app/webroot/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0056</td><td bgcolor='#eeeeec' align='right'>746496</td><td bgcolor='#eeeeec'>Dispatcher->dispatch(  )</td><td title='/www/app/webroot/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>108</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0083</td><td bgcolor='#eeeeec' align='right'>830936</td><td bgcolor='#eeeeec'>Dispatcher->_invoke(  )</td><td title='/www/lib/Cake/Routing/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>167</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0370</td><td bgcolor='#eeeeec' align='right'>1638408</td><td bgcolor='#eeeeec'>Controller->invokeAction(  )</td><td title='/www/lib/Cake/Routing/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>193</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0370</td><td bgcolor='#eeeeec' align='right'>1638536</td><td bgcolor='#eeeeec'><a href='http://www.php.net/ReflectionMethod.invokeArgs' target='_new'>invokeArgs</a>
(  )</td><td title='/www/lib/Cake/Controller/Controller.php' bgcolor='#eeeeec'>.../Controller.php<b>:</b>491</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.0370</td><td bgcolor='#eeeeec' align='right'>1638544</td><td bgcolor='#eeeeec'>TechnicalController->knowledgebase(  )</td><td title='/www/lib/Cake/Controller/Controller.php' bgcolor='#eeeeec'>.../Controller.php<b>:</b>491</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.0409</td><td bgcolor='#eeeeec' align='right'>1942648</td><td bgcolor='#eeeeec'>Thybag\SharePointAPI->getLists(  )</td><td title='/www/app/Controller/TechnicalController.php' bgcolor='#eeeeec'>.../TechnicalController.php<b>:</b>24</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.0409</td><td bgcolor='#eeeeec' align='right'>1942648</td><td bgcolor='#eeeeec'>SoapClient->GetListCollection(  )</td><td title='/www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php' bgcolor='#eeeeec'>.../SharePointAPI.php<b>:</b>278</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.0409</td><td bgcolor='#eeeeec' align='right'>1942704</td><td bgcolor='#eeeeec'><a href='http://www.php.net/SoapClient.--call' target='_new'>__call</a>
(  )</td><td title='/www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php' bgcolor='#eeeeec'>.../SharePointAPI.php<b>:</b>278</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.0520</td><td bgcolor='#eeeeec' align='right'>1943680</td><td bgcolor='#eeeeec'>Thybag\Auth\SharePointOnlineAuth->__doRequest(  )</td><td title='/www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php' bgcolor='#eeeeec'>.../SharePointAPI.php<b>:</b>278</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.0520</td><td bgcolor='#eeeeec' align='right'>1943680</td><td bgcolor='#eeeeec'>Thybag\Auth\SharePointOnlineAuth->configureAuthCookies(  )</td><td title='/www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/Auth/SharePointOnlineAuth.php' bgcolor='#eeeeec'>.../SharePointOnlineAuth.php<b>:</b>20</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.0520</td><td bgcolor='#eeeeec' align='right'>1945952</td><td bgcolor='#eeeeec'>Thybag\Auth\SharePointOnlineAuth->authCurl(  )</td><td title='/www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/Auth/SharePointOnlineAuth.php' bgcolor='#eeeeec'>.../SharePointOnlineAuth.php<b>:</b>90</td></tr>
'
	[protected] message => 'Curl error: Connection timed out after 10000 milliseconds'
	[protected] code => (int) 0
	[protected] file => '/www/app/Vendor/thybag/php-sharepoint-lists-api/src/Thybag/Auth/SharePointOnlineAuth.php'
	[protected] line => (int) 192
}

```

from the following controller code:

```
  public function knowledgebase() {
    $file = WWW_ROOT . 'files' . DS . 'Lists.asmx';
    $sp = new SharePointAPI('barry.denson@kip.kingspan.net', 'password', $file, 'SPONLINE');  
    $sp->getLists();
    $this->set('page_title', __('Knowledgebase'));
  }

```

**Comment by densonclan** [comment]
In fact I get this error regardless of the action I try to take.

**Comment by densonclan** [comment]
After further testing it looks like this issue was a server firewall issue.

**Comment by ccarlosm** [comment]
Hi desonclan,

I am getting same problem, did you find the solution?

Fatal error: Uncaught Exception: Error (Receiver) Operation timed out after 10000 milliseconds with 6524424689811456 out of 7582833480564736 bytes received,more= in G:\xampp\htdocs\sharepoint\wp-content\vendor\thybag\php-sharepoint-lists-api\src\Thybag\SharePointAPI.php:1033 Stack trace: #0 G:\xampp\htdocs\sharepoint\wp-content\vendor\thybag\php-sharepoint-lists-api\src\Thybag\SharePointAPI.php(483): Thybag\SharePointAPI->onError(Object(SoapFault)) #1 G:\xampp\htdocs\sharepoint\wp-content\themes\madrilena\cups.php(28): Thybag\SharePointAPI->getItem('https://madrile...') #2 G:\xampp\htdocs\sharepoint\wp-includes\template-loader.php(77): include('G:\\xampp\\htdocs...') #3 G:\xampp\htdocs\sharepoint\wp-blog-header.php(19): require_once('G:\\xampp\\htdocs...') #4 G:\xampp\htdocs\sharepoint\index.php(17): require('G:\\xampp\\htdocs...') #5 {main} thrown in G:\xampp\htdocs\sharepoint\wp-content\vendor\thybag\php-sharepoint-lists-api\src\Thybag\SharePointAPI.php on line 1033

Thanks in advance!

**Comment by ccarlosm** [comment]
> After further testing it looks like this issue was a server firewall issue.

Hi desonclan,

I am getting same problem, did you find the solution?

Fatal error: Uncaught Exception: Error (Receiver) Operation timed out after 10000 milliseconds with 6524424689811456 out of 7582833480564736 bytes received,more= in G:\xampp\htdocs\sharepoint\wp-content\vendor\thybag\php-sharepoint-lists-api\src\Thybag\SharePointAPI.php:1033 Stack trace: #0 G:\xampp\htdocs\sharepoint\wp-content\vendor\thybag\php-sharepoint-lists-api\src\Thybag\SharePointAPI.php(483): Thybag\SharePointAPI->onError(Object(SoapFault)) #1 G:\xampp\htdocs\sharepoint\wp-content\themes\madrilena\cups.php(28): Thybag\SharePointAPI->getItem('https://madrile...') #2 G:\xampp\htdocs\sharepoint\wp-includes\template-loader.php(77): include('G:\xampp\htdocs...') #3 G:\xampp\htdocs\sharepoint\wp-blog-header.php(19): require_once('G:\xampp\htdocs...') #4 G:\xampp\htdocs\sharepoint\index.php(17): require('G:\xampp\htdocs...') #5 {main} thrown in G:\xampp\htdocs\sharepoint\wp-content\vendor\thybag\php-sharepoint-lists-api\src\Thybag\SharePointAPI.php on line 1033

Thanks in advance!
